version: '3'
services:
  server:
    build: .
    links:
      - postgres
    depends_on:
      - postgres
    ports:
      - '${SERVER_PORT}:4000'
      - '${STUDIO_PORT}:5555'
    environment:
      NODE_ENV: ${NODE_ENV}
      DATABASE_URL: ${DATABASE_URL}
      APP_SECRET: ${APP_SECRET}
    networks:
      - server-network
  postgres:
    image: postgres:12.5
    restart: always
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
      POSTGRES_DB: prisma
    networks:
      server-network:
        aliases:
          - postgresql.db
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:
networks:
  server-network:
