version: '3'
services:
  server:
    build: .
    links:
      - mysql
    depends_on:
      - mysql
    ports:
      - '${SERVER_PORT}:4000'
      - '${STUDIO_PORT}:5555'
    environment:
      NODE_ENV: ${NODE_ENV}
      MYSQL_URL: ${MYSQL_URL}
      APP_SECRET: ${APP_SECRET}
    networks:
      - server-network
  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_USER: prisma
      MYSQL_PASSWORD: prisma
      MYSQL_DB: prisma
    networks:
      server-network:
        aliases:
          - mysql.db
    volumes:
      - mysql:/var/lib/mysql/data
volumes:
  mysql:
networks:
  server-network:
